### ISSUE TITLE
这和原版有什么区别?

### ISSUE THREAD

**Issue by tennessine** [vipshop/twemproxy-vip#1]

**Comment by tennessine** [comment]
怎么又跟zookeeper搞一起了

**Comment by deep011** [comment]
https://github.com/vipshop/twemproxy-vip/wiki/twemproxy%E5%9C%A8%E5%94%AF%E5%93%81%E4%BC%9A%E7%9A%84%E7%BB%B4%E6%8A%A4%E7%89%88%E6%9C%AC
